version: 2
before:
  hooks:
  - go generate ./...
  - go mod tidy
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  goarch:
  - amd64
  - arm64
  binary: '{{ .ProjectName }}'
  ignore:
  - goos: windows
    goarch: arm64
dockers_v2:
- images:
    - "ghcr.io/miguelangel-nubla/{{.ProjectName}}"
  tags:
    - "{{ .Tag }}"
    - "v{{ .Major }}"
    - "v{{ .Major }}.{{ .Minor }}"
    - "latest"
  dockerfile: 'Dockerfile.goreleaser'
  build_args:
    BINARY: "{{ .ProjectName }}"
  platforms:
    - "linux/amd64"
    - "linux/arm64"
  flags:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.url=https://github.com/miguelangel-nubla/{{ .ProjectName }}"
    - "--label=org.opencontainers.image.source=https://github.com/miguelangel-nubla/{{ .ProjectName }}"
  extra_files:
    - LICENSE
archives:

- files:
  - LICENSE*
  - README*
  - CHANGELOG*
  formats: tar.gz
  name_template: >-
    {{ .ProjectName }}_ {{- title .Os }}_ {{- if eq .Arch "amd64" }}x86_64 {{- else if eq .Arch "386" }}i386 {{- else }}{{ .Arch }}{{ end }} {{- if .Arm }}v{{ .Arm }}{{ end }}
  format_overrides:
  - goos: windows
    formats: zip

checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj